# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='img/category/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('shows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorysubcategory_requests_category', to='service.Category')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorysubcategory_requests_subcategory', to='service.Category')),
            ],
        ),
    ]
