# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
